### PR TITLE
Fix test to handle rounding errors

### LINKED ISSUE #276: [Bug]: Multipatch connectivity tests are susceptible to rounding errors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

The tests `OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest` and `OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest` use hard-coded values to test whether coordinates are placed on the correct patch. Some of those values are supposed to be on the patch boundary. As truncation and rounding errors can lead to slightly different results with different compilers this does not always give the expected result.

For values on the boundary `ddc::coordinate` should be used to get the boundary coordinate instead of hard coding values.

### Version of the code used

67a30189c3a1d4e2662416acb4d84113b80dd02a

### Steps to Reproduce

Compile `unit_tests_connectivity` with a clang compiler.
Run:
```
ctest -R CzarnyOnionPatchLocator2PatchesTest
```

<details>

You will see:
```
Test project /home/emily/Code/gyselalibxx_github/build_clang
    Start 411: OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest
1/2 Test #411: OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest ...***Failed    0.02 sec
Note: Google Test filter = OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from OnionPatchLocator2PatchesTest
[ RUN      ] OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest
/home/emily/Code/gyselalibxx_github/tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:95: Failure
Expected equality of these values:
  failed_attempt
    Which is: 1
  0
[  FAILED  ] OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest (0 ms)
[----------] 1 test from OnionPatchLocator2PatchesTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest

 1 FAILED TEST

    Start 413: OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest
2/2 Test #413: OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest .....***Failed    0.02 sec
Note: Google Test filter = OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from OnionPatchLocator2PatchesTest
[ RUN      ] OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest
/home/emily/Code/gyselalibxx_github/tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:307: Failure
Expected equality of these values:
  patch_locator(coord)
    Which is: -1
  1
[  FAILED  ] OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest (0 ms)
[----------] 1 test from OnionPatchLocator2PatchesTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest

 1 FAILED TEST


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.05 sec

The following tests FAILED:
	411 - OnionPatchLocator2PatchesTest.DeviceCzarnyOnionPatchLocator2PatchesTest (Failed)
	413 - OnionPatchLocator2PatchesTest.HostCzarnyOnionPatchLocator2PatchesTest (Failed)
Errors while running CTest
```

</details>

### Environment

I can reproduce on the clang CI (see #275) and on my personal computer (linux).
In both cases this is a CPU environment.

### How does this bug impact your work?

Minor - It’s an inconvenience, but I can work around it.

### PR DESCRIPTION
**Pull request by EmilyBourne**
Fix multipatch connectivity tests to make them less susceptible to rounding errors. Fixes #276

### CODE REVIEW

**Comment by EmilyBourne** [comment]
Locally this has been shown to fix the clang compilation issue

**Review by tpadioleau — APPROVED** [review]
LGTM but let's wait also @PaulineVidal

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 1]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+        patches_host(1) = 0;
+    }
+    // Test in patch 1
     patches_host(2) = 0;
+    // Test in patch 2
     patches_host(3) = 1;
-    patches_host(4) = 1;
-    patches_host(5) = 1;
+    // Test patch boundary
+    if (ddc::select<R>(to_logical_mapping(coords_host(4))) - 1 <= 0) {
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:235]:
```suggestion
    if (ddc::select<R>(to_logical_mapping(coords_host(4))) - r1_max <= 0) {
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 2]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
 
+    // Test outside range (below)
     coords_host(0) = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(0, 0)));
+    // Test lower bound
     coords_host(1) = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(0.2, 0)));
+    // Test in patch 1
     coords_host(2) = PhysicalCoordXY(0.25, .03);
+    // Test in patch 2
     coords_host(3) = PhysicalCoordXY(1, 1);
+    // Test patch boundary
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:215]:
```suggestion
    // Test patch interface
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 3]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+    } else {
+        patches_host(1) = 0;
+    }
+    // Test in patch 1
     patches_host(2) = 0;
+    // Test in patch 2
     patches_host(3) = 1;
-    patches_host(4) = 1;
-    patches_host(5) = 1;
+    // Test patch boundary
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:234]:
```suggestion
    // Test patch interface
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 4]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+    if (ddc::select<R>(to_logical_mapping(coords_host(4))) - 1 <= 0) {
+        patches_host(4) = 0;
+    } else {
+        patches_host(4) = 1;
+    }
+    // Test upper bound
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:240]:
```suggestion
    // Test radial upper bound
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 5]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+    if (ddc::select<R>(to_logical_mapping(coords_host(5))) - 1.5 <= 0) {
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:241]:
```suggestion
    if (ddc::select<R>(to_logical_mapping(coords_host(5))) - r2_max <= 0) {
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 6]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+        patches_host(5) = 1;
+    } else {
+        patches_host(5) = PatchLocator::outside_rmax_domain;
+    }
+    // Test outside range (above)
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:246]:
```suggestion
    // Test outside domain (radius bigger than the maximum radius)
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 7]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
             Kokkos::DefaultHostExecutionSpace>
             patch_locator(all_idx_ranges, to_physical_mapping, to_logical_mapping);
 
+    // Test outside range (below)
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:317]:
```suggestion
    // Test outside domain (radius smaller than the minimum radius)
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 8]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
     PhysicalCoordXY coord(-0.05, .03);
     EXPECT_EQ(patch_locator(coord), PatchLocator::outside_rmin_domain);
 
+    // Test lower bound
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:321]:
```suggestion
    // Test radial lower bound
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 9]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
     coord = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(0.2, 0)));
-    EXPECT_EQ(patch_locator(coord), 0);
+    if (ddc::select<R>(to_logical_mapping(coord)) - 0.2 < 0) {
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:323]:
```suggestion
    if (ddc::select<R>(to_logical_mapping(coord)) - r1_min < 0) {
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 10]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
 
+    // Test in patch 1
     coord = PhysicalCoordXY(0.25, .03);
     EXPECT_EQ(patch_locator(coord), 0);
 
+    // Test in patch 2
     coord = PhysicalCoordXY(1, 1);
     EXPECT_EQ(patch_locator(coord), 1);
 
+    // Test patch boundary
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:337]:
```suggestion
    // Test patch interface
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 11]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
     coord = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(1, 0)));
-    EXPECT_EQ(patch_locator(coord), 1);
+    if (ddc::select<R>(to_logical_mapping(coord)) - 1 <= 0) {
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:339]:
```suggestion
    if (ddc::select<R>(to_logical_mapping(coord)) - r1_max <= 0) {
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 12]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
+        EXPECT_EQ(patch_locator(coord), 0);
+    } else {
+        EXPECT_EQ(patch_locator(coord), 1);
+    }
 
+    // Test upper bound
     coord = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(1.5, 0)));
-    EXPECT_EQ(patch_locator(coord), 1);
+    if (ddc::select<R>(to_logical_mapping(coord)) - 1.5 <= 0) {
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:347]:
```suggestion
    if (ddc::select<R>(to_logical_mapping(coord)) - r2_max <= 0) {
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 13]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
+    // Test patch boundary
     coord = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(1, 0)));
-    EXPECT_EQ(patch_locator(coord), 1);
+    if (ddc::select<R>(to_logical_mapping(coord)) - 1 <= 0) {
+        EXPECT_EQ(patch_locator(coord), 0);
+    } else {
+        EXPECT_EQ(patch_locator(coord), 1);
+    }
 
+    // Test upper bound
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:345]:
```suggestion
    // Test radial upper bound
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 14]
```diff
@@ -288,24 +314,43 @@ TEST_F(OnionPatchLocator2PatchesTest, HostCzarnyOnionPatchLocator2PatchesTest)
...
     coord = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(1.5, 0)));
-    EXPECT_EQ(patch_locator(coord), 1);
+    if (ddc::select<R>(to_logical_mapping(coord)) - 1.5 <= 0) {
+        EXPECT_EQ(patch_locator(coord), 1);
+    } else {
+        EXPECT_EQ(patch_locator(coord), PatchLocator::outside_rmax_domain);
+    }
 
+    // Test outside range (above)
```
Comment (PaulineVidal) [inline tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp:353]:
```suggestion
    // Test outside domain (radius bigger than the maximum radius)
```

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp [hunk 15]
```diff
@@ -204,20 +204,46 @@ TEST_F(OnionPatchLocator2PatchesTest, DeviceCzarnyOnionPatchLocator2PatchesTest)
...
+    // Test upper bound
     coords_host(5) = PhysicalCoordXY(to_physical_mapping(Coord<R, Theta>(1.5, 0)));
+    // Test outside range (above)
     coords_host(6) = PhysicalCoordXY(-2.1, 0);
 
+    // Test outside range (below)
     patches_host(0) = PatchLocator::outside_rmin_domain;
-    patches_host(1) = 0;
+    // Test lower bound
+    if (ddc::select<R>(to_logical_mapping(coords_host(1))) - 0.2 < 0) {
```
[the remark this answers is not in the document]
Comment (EmilyBourne) [reply tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp]: Fixed bc6518e1b

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp (hunk 1 above)
Comment (EmilyBourne) [reply tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp]: Fixed bc6518e1b

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp (hunk 9 above)
Comment (EmilyBourne) [reply tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp]: Fixed bc6518e1b

File: tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp (hunk 12 above)
Comment (EmilyBourne) [reply tests/multipatch/connectivity/patch_locator_onion_shape_2patches.cpp]: Fixed bc6518e1b

**Review by PaulineVidal — APPROVED** [review]
